### ISSUE TITLE
Make a dark theme

### ISSUE THREAD

**Issue by guvarallo** [guvarallo/selfolio#1]
A good improvement would be to have a button in the top of the page to switch from light to dark theme!

**Comment by utkarsh4321** [comment]
Hii @guvarallo i want to contribute into this can I help into this

**Comment by guvarallo** [comment]
Hi @utkarsh4321, sure go ahead

**Comment by utkarsh4321** [comment]
Hii @guvarallo is there any preferred colour scheme for the dark theme so I will start working on it

**Comment by guvarallo** [comment]
Hey @utkarsh4321 I think would be cool to also choose the dark theme color scheme

**Comment by utkarsh4321** [comment]
what you want a toggle switch that toggles between dark and light theme or colour selection scheme so that we choose a different colour to change portfolio theme.
